/*******************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Christoph Läubrich - initial API and implementation
 *******************************************************************************/
package org.eclipse.osgi.technology.webservices.weaving;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;

import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.InvalidSyntaxException;
import org.osgi.framework.Version;
import org.osgi.framework.hooks.weaving.WeavingHook;
import org.osgi.framework.hooks.weaving.WovenClass;
import org.osgi.framework.wiring.BundleRequirement;
import org.osgi.framework.wiring.BundleWiring;
import org.osgi.namespace.implementation.ImplementationNamespace;
import org.osgi.service.webservice.whiteboard.WebserviceWhiteboardConstants;

/**
 * A {@link WeavingHook} that automatically adds dynamic imports for
 * {@code jakarta.xml.bind.annotation} packages to any bundle that requires the
 * OSGi webservice whiteboard implementation. This relieves bundles from having
 * to declare this dependency explicitly, in case code is generated by the
 * jax-ws runtime implementation for annotated webservice classes.
 */
public class WebserviceWeavingHook implements WeavingHook {

    private static final Map<String, Comparable<?>> MAP = Map.of(ImplementationNamespace.IMPLEMENTATION_NAMESPACE,
            WebserviceWhiteboardConstants.WEBSERVICE_IMPLEMENTATION, "version",
            Version.valueOf(WebserviceWhiteboardConstants.WEBSERVICE_SPECIFICATION_VERSION));

    private static final List<String> DYNAMIC_IMPORTS = List.of("jakarta.xml.bind.annotation");

    private final Set<Bundle> webserviceBundles = Collections.synchronizedSet(
            Collections.newSetFromMap(new WeakHashMap<>()));

    private final Set<Bundle> ignoredBundles = Collections.synchronizedSet(
            Collections.newSetFromMap(new WeakHashMap<>()));

    @Override
    public void weave(WovenClass wovenClass) {
        BundleWiring wiring = wovenClass.getBundleWiring();
        Bundle bundle = wiring.getBundle();

        if (ignoredBundles.contains(bundle)) {
            return;
        }

        if (!webserviceBundles.contains(bundle)) {
            if (requiresWebserviceImplementation(wiring)) {
                webserviceBundles.add(bundle);
            } else {
                ignoredBundles.add(bundle);
                return;
            }
        }

        List<String> dynamicImports = wovenClass.getDynamicImports();
        for (String pkg : DYNAMIC_IMPORTS) {
            if (!dynamicImports.contains(pkg)) {
                dynamicImports.add(pkg);
            }
        }
    }

    private boolean requiresWebserviceImplementation(BundleWiring wiring) {
        List<BundleRequirement> requirements = wiring
                .getRequirements(ImplementationNamespace.IMPLEMENTATION_NAMESPACE);
        for (BundleRequirement req : requirements) {
            String filter = req.getDirectives().get("filter");
            if (filter != null) {
                try {
                    if (FrameworkUtil.createFilter(filter).matches(MAP)) {
                        return true;
                    }
                } catch (InvalidSyntaxException e) {
                    //should not happen but if we can not check...
                }
            }
        }
        return false;
    }
}
