name: Verify Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    branches: 
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'this'
    - name: Checkout OSGi PR
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'osgi'
       repository: 'laeubi/osgi'
       ref: 'design/587'
    - name: Set up Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        cache: 'maven'
        java-version: 17
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.9
    - name: Build OSGi PR
      working-directory: 'osgi'
      run: ./gradlew :build :publish
    - name: Run Build
      working-directory: 'this'
      run: mvn -B verify
